/**
 * Seed accounts loaded into the store on first run.
 * Production: administrator accounts only (development/demo role accounts removed).
 */
const SEED_USERS = [
  {
    username: 'admin',
    password: 'a3c1993',
    role: 'admin',
    displayName: 'System Administrator',
    employeeId: 'EMP-ADMIN001',
    email: 'admin@rms.local',
    department: 'Information Technology',
    position: 'System Administrator',
    builtIn: true,
    canManageUsers: true,
  },
  {
    username: 'sys-admin',
    password: 'a3c2026',
    role: 'admin',
    displayName: 'IT Systems Administrator',
    employeeId: 'EMP-SYSADM01',
    email: 'sysadmin@rms.local',
    department: 'Information Technology',
    position: 'System Administrator',
    builtIn: true,
    canManageUsers: true,
  },
  {
    username: 'it-head',
    password: 'dept2026',
    role: 'dept_head',
    displayName: 'IT Department Head',
    employeeId: 'EMP-ITHEAD01',
    email: 'it.head@rms.local',
    department: 'Information Technology',
    position: 'Vice President — Information Technology',
  },
  {
    username: 'fin-head',
    password: 'dept2026',
    role: 'dept_head',
    displayName: 'Finance Department Head',
    employeeId: 'EMP-FINHEAD1',
    email: 'finance.head@rms.local',
    department: 'Finance',
    position: 'Vice President — Finance',
  },
  {
    username: 'ops-head',
    password: 'dept2026',
    role: 'dept_head',
    displayName: 'Operations Department Head',
    employeeId: 'EMP-OPSHEAD1',
    email: 'operations.head@rms.local',
    department: 'Operations',
    position: 'Vice President — Operations',
  },
  {
    username: 'admin-head',
    password: 'dept2026',
    role: 'dept_head',
    displayName: 'Administration Department Head',
    employeeId: 'EMP-ADMHEAD1',
    email: 'admin.head@rms.local',
    department: 'Administration',
    position: 'Vice President — Administration',
  },
  {
    username: 'rm-officer',
    password: 'a3c2026',
    role: 'rm_officer',
    displayName: 'Risk Governance Office',
    employeeId: 'EMP-RMU001',
    email: 'rmu@rms.local',
    department: 'RMO',
    position: 'Risk Governance Officer',
  },
  {
    username: 'president',
    password: 'a3c2026',
    role: 'president',
    displayName: 'President & CEO',
    employeeId: 'EMP-PCEO001',
    email: 'president@rms.local',
    department: 'PCEO',
    position: 'President and Chief Executive Officer',
  },
  {
    username: 'executive',
    password: 'a3c2026',
    role: 'executive',
    displayName: 'Executive Committee',
    employeeId: 'EMP-EXEC001',
    email: 'executive@rms.local',
    department: 'PCEO',
    position: 'Executive Committee Member',
  },
  {
    username: 'reporter',
    password: 'a3c2026',
    role: 'supervisor',
    displayName: 'Risk Ticket Reporter',
    employeeId: 'EMP-RPT001',
    email: 'reporter@rms.local',
    department: 'Operations',
    position: 'Department Supervisor',
  },
  {
    username: 'compliance',
    password: 'a3c2026',
    role: 'audit_officer',
    displayName: 'Compliance Officer',
    employeeId: 'EMP-COMP001',
    email: 'compliance@rms.local',
    department: 'Internal Audit',
    position: 'Compliance Officer',
  },
];

module.exports = { SEED_USERS };
