/**
 * Seed accounts loaded into the store on first run (and kept in sync on restart).
 * Usernames are stored lowercase; login is case-insensitive.
 */
const SEED_USERS = [
  {
    username: 'admin',
    password: 'a3c1993',
    role: 'admin',
    displayName: 'System Administrator',
    employeeId: 'EMP-001',
    email: 'admin@rms.local',
    department: 'Information Technology',
    position: 'System Administrator',
    builtIn: true,
    canManageUsers: true,
  },
  {
    username: 'sys-admin',
    password: 'a3c2026',
    role: 'admin',
    displayName: 'System Administrator',
    employeeId: 'EMP-002',
    email: 'sysadmin@rms.local',
    department: 'Information Technology',
    position: 'System Administrator',
    builtIn: true,
    canManageUsers: true,
  },
  {
    username: 'reporter',
    password: 'a3c1993',
    role: 'supervisor',
    displayName: 'Ticket Reporter',
    employeeId: 'EMP-010',
    email: 'reporter@rms.local',
    department: 'Operations',
    position: 'Risk Reporter',
  },
  {
    username: 'dephead',
    password: 'a3c1993',
    role: 'dept_head',
    displayName: 'IT Department Head',
    employeeId: 'EMP-011',
    email: 'dephead@rms.local',
    department: 'Information Technology',
    position: 'Department Head / Vice President',
  },
  {
    username: 'mmcd',
    password: 'a3c1993',
    role: 'dept_head',
    displayName: 'MMCD Department Head',
    employeeId: 'EMP-012',
    email: 'mmcd@rms.local',
    department: 'MMCD',
    position: 'Department Head / Vice President',
  },
  {
    username: 'finance',
    password: 'a3c1993',
    role: 'dept_head',
    displayName: 'Finance Department Head',
    employeeId: 'EMP-013',
    email: 'finance@rms.local',
    department: 'Finance',
    position: 'Department Head / Vice President',
  },
  {
    username: 'operations',
    password: 'a3c1993',
    role: 'dept_head',
    displayName: 'Operations Department Head',
    employeeId: 'EMP-014',
    email: 'operations@rms.local',
    department: 'Operations',
    position: 'Department Head / Vice President',
  },
  {
    username: 'adminsupport',
    password: 'a3c1993',
    role: 'dept_head',
    displayName: 'Admin Department Head',
    employeeId: 'EMP-015',
    email: 'adminsupport@rms.local',
    department: 'Administration',
    position: 'Department Head / Vice President',
  },
  {
    username: 'hrms',
    password: 'a3c1993',
    role: 'dept_head',
    displayName: 'HRM Department Head',
    employeeId: 'EMP-016',
    email: 'hrms@rms.local',
    department: 'HRMS',
    position: 'Department Head / Vice President',
  },
  {
    username: 'rmo',
    password: 'a3c1993',
    role: 'rm_officer',
    displayName: 'Risk Management Officer',
    employeeId: 'EMP-017',
    email: 'rmo@rms.local',
    department: 'RMO',
    position: 'Risk Management Officer',
  },
  {
    username: 'pceo',
    password: 'a3c1993',
    role: 'president',
    displayName: 'President / CEO',
    employeeId: 'EMP-018',
    email: 'pceo@rms.local',
    department: 'PCEO',
    position: 'President / CEO',
  },
  {
    username: 'executive',
    password: 'a3c1993',
    role: 'executive',
    displayName: 'Executive Members',
    employeeId: 'EMP-009',
    email: 'executive@rms.local',
    department: 'PCEO',
    position: 'Executive Committee Member',
  },
  {
    username: 'nbo',
    password: 'a3c1993',
    role: 'dept_head',
    displayName: 'New Business Operations',
    employeeId: 'EMP-019',
    email: 'nbo@rms.local',
    department: 'New Business Operations',
    position: 'Department Head / Vice President',
  },
  // Legacy usernames kept so older login sheets still work.
  {
    username: 'it-head',
    password: 'dept2026',
    role: 'dept_head',
    displayName: 'IT Department Head',
    employeeId: 'EMP-003',
    email: 'it.head@rms.local',
    department: 'Information Technology',
    position: 'Department Head / Vice President',
  },
  {
    username: 'fin-head',
    password: 'dept2026',
    role: 'dept_head',
    displayName: 'Finance Department Head',
    employeeId: 'EMP-004',
    email: 'finance.head@rms.local',
    department: 'Finance',
    position: 'Department Head / Vice President',
  },
  {
    username: 'ops-head',
    password: 'dept2026',
    role: 'dept_head',
    displayName: 'Operations Department Head',
    employeeId: 'EMP-005',
    email: 'operations.head@rms.local',
    department: 'Operations',
    position: 'Department Head / Vice President',
  },
  {
    username: 'admin-head',
    password: 'dept2026',
    role: 'dept_head',
    displayName: 'Administration Department Head',
    employeeId: 'EMP-006',
    email: 'admin.head@rms.local',
    department: 'Administration',
    position: 'Department Head / Vice President',
  },
  {
    username: 'rm-officer',
    password: 'a3c2026',
    role: 'rm_officer',
    displayName: 'Risk Management Officer',
    employeeId: 'EMP-007',
    email: 'rm-officer@rms.local',
    department: 'RMO',
    position: 'Risk Management Officer',
  },
  {
    username: 'president',
    password: 'a3c2026',
    role: 'president',
    displayName: 'President & CEO',
    employeeId: 'EMP-008',
    email: 'president@rms.local',
    department: 'PCEO',
    position: 'President / CEO',
  },
];

module.exports = { SEED_USERS };
