/**
 * Seed accounts loaded into the store on first run.
 * Production: administrator accounts only (development/demo role accounts removed).
 */
const SEED_USERS = [
  {
    username: 'admin',
    password: 'a3c1993',
    role: 'admin',
    displayName: 'System Administrator',
    employeeId: 'EMP-001',
    email: 'admin@rms.local',
    department: 'Information Technology',
    position: 'System Administrator',
    builtIn: true,
    canManageUsers: true,
  },
  {
    username: 'sys-admin',
    password: 'a3c2026',
    role: 'admin',
    displayName: 'IT Systems Administrator',
    employeeId: 'EMP-002',
    email: 'sysadmin@rms.local',
    department: 'Information Technology',
    position: 'System Administrator',
    builtIn: true,
    canManageUsers: true,
  },
  {
    username: 'it-head',
    password: 'dept2026',
    role: 'dept_head',
    displayName: 'IT Department Head',
    employeeId: 'EMP-003',
    email: 'it.head@rms.local',
    department: 'Information Technology',
    position: 'Department Head / Vice President',
  },
  {
    username: 'fin-head',
    password: 'dept2026',
    role: 'dept_head',
    displayName: 'Finance Department Head',
    employeeId: 'EMP-004',
    email: 'finance.head@rms.local',
    department: 'Finance',
    position: 'Department Head / Vice President',
  },
  {
    username: 'ops-head',
    password: 'dept2026',
    role: 'dept_head',
    displayName: 'Operations Department Head',
    employeeId: 'EMP-005',
    email: 'operations.head@rms.local',
    department: 'Operations',
    position: 'Department Head / Vice President',
  },
  {
    username: 'admin-head',
    password: 'dept2026',
    role: 'dept_head',
    displayName: 'Administration Department Head',
    employeeId: 'EMP-006',
    email: 'admin.head@rms.local',
    department: 'Administration',
    position: 'Department Head / Vice President',
  },
  {
    username: 'rm-officer',
    password: 'a3c2026',
    role: 'rm_officer',
    displayName: 'Risk Management Officer',
    employeeId: 'EMP-007',
    email: 'rmo@rms.local',
    department: 'RMO',
    position: 'Risk Management Officer',
  },
  {
    username: 'president',
    password: 'a3c2026',
    role: 'president',
    displayName: 'President & CEO',
    employeeId: 'EMP-008',
    email: 'president@rms.local',
    department: 'PCEO',
    position: 'President / CEO',
  },
  {
    username: 'executive',
    password: 'a3c2026',
    role: 'executive',
    displayName: 'Executive Committee',
    employeeId: 'EMP-009',
    email: 'executive@rms.local',
    department: 'PCEO',
    position: 'Executive Committee Member',
  },
  {
    username: 'reporter',
    password: 'a3c2026',
    role: 'supervisor',
    displayName: 'Risk Ticket Reporter',
    employeeId: 'EMP-010',
    email: 'reporter@rms.local',
    department: 'Operations',
    position: 'Risk Reporter',
  },
];

module.exports = { SEED_USERS };
